name: Sound of Text WA Official
title: Sound of Text WA Official
description: Latest sound of text WA tutorials
logo: assets/images/idnlogos.png
favicon: assets/images/techico.png
url: 'https://soundoftextwa.github.io '
baseurl: ''
google_analytics: 'UA-209667013-4'
include:
  - _pages
permalink: '/:title/'
authors:
  techidn:
    name: Soundoftextwa
    display_name: Soundoftextwa
    email: sultanhamidd6@gmail.com
    twitter: ''
    description: "Text to speech technology enthusiast, developer and owner of Sound of Text WA Official"
    web: "https://www.soundoftext.com"
    gravatar: 7ae47ed8e06cdf6ec282793d482f3afb
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
paginate: 6
paginate_path: '/page:num/'
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
adsense: 'disabled'
adsense-data-ad-client: ''
adsense-data-ad-slot: ''
lazyimages: 'enabled'
exclude:
  - changelog.md
  - LICENSE.txt
  - README.md
  - Gemfile
  - Gemfile.lock
jekyll_admin:
  hidden_links:
    - datafiles
